version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/udaraw.com

    steps:
      - checkout
      - add_ssh_keys
      - deploy: # Build
          name: Deploy
          working_directory: ~/udaraw.com
          command: |
            scp -r ~/udaraw "$SSH_USER@$SSH_HOST:$SSH_DEPLOY_PATH"