version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/udaraw

    steps:
      - checkout
      - add_ssh_keys
      - deploy: # Build
          name: Deploy
          command: echo 'h'