version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - deploy: # Build
          name: Deploy
          steps:
            deploy-job:
              steps:
                - add_ssh_keys