version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/udaraw.com

    steps:
      - checkout
      - add_ssh_keys:
        - fingerprints:
          - "SHA256:H/wROZlHF5MbQcMTG82bqa9tThTnp+EbIRYNyXdj6+I"
      - deploy: # Build
          name: Deploy
          working_directory: ~/udaraw.com
          command: |
            scp -r ~/udaraw.com "$SSH_USER@$SSH_HOST:$SSH_DEPLOY_PATH"